-- =============================================
-- Sample Data Insertion Script
-- Assumes tables created by EF Core Migrations
-- Uses SQL Server syntax for IDENTITY_INSERT
-- Assumes PhoneNumber is a single column in Users table
-- Uses the actual generated hash for the password "almafa123"
-- =============================================

-- Enable explicit ID insertion for Addresses
SET IDENTITY_INSERT Addresses ON;

-- Insert Sample Addresses
INSERT INTO Addresses (Id, ZipCode, Country, County, Settlement, Street, HouseNumber, Floor, Door) VALUES
(1, '8200', 'Hungary', 'Veszprém', 'Veszprém', 'Egyetem utca', '10', NULL, NULL),
(2, '1054', 'Hungary', 'Budapest', 'Budapest', 'Kossuth Lajos tér', '1-3', '2', '5'),
(3, '4032', 'Hungary', 'Hajdú-Bihar', 'Debrecen', 'Egyetem sugárút', '1', NULL, NULL);

-- Disable explicit ID insertion for Addresses
SET IDENTITY_INSERT Addresses OFF;


-- Enable explicit ID insertion for Roles (Optional if already seeded by EF)
-- If EF already seeded these, you can skip this Roles block
SET IDENTITY_INSERT Roles ON;

-- Insert Sample Roles (Assuming IDs 1, 2, 3, 4)
-- Make sure these match the names used in your C# code logic
INSERT INTO Roles (Id, Name) VALUES
(1, 'Guest'),  -- Assuming ID 1
(2, 'User'),   -- Assuming ID 2
(3, 'Admin'),  -- Assuming ID 3
(4, 'Director'); -- Assuming ID 4

-- Disable explicit ID insertion for Roles
SET IDENTITY_INSERT Roles OFF;


-- Enable explicit ID insertion for Users
SET IDENTITY_INSERT Users ON;

-- Insert Sample Users
-- !! IMPORTANT !! Replace the placeholder below with the ACTUAL HASH generated by:
-- C#: Console.WriteLine(BCrypt.Net.BCrypt.HashPassword("almafa123"));
INSERT INTO Users (Id, UserName, FirstName, LastName, Email, Password, PhoneNumber, AddressId) VALUES
(1, 'admin_user', 'Ad', 'Min', 'admin@berauto.test', '$2a$11$Yj7U.vAlnrczdOxT7jWNpuLIywZNnN3GUKkTGkbG45vG2M86VuRr.', '+36301112233', 1), -- Uses Address ID 1
(2, 'test_user', 'Teszt', 'Elek', 'test@berauto.test', '$2a$11$Yj7U.vAlnrczdOxT7jWNpuLIywZNnN3GUKkTGkbG45vG2M86VuRr.', '+36207778899', 2), -- Uses Address ID 2
(3, 'director_user', 'Dir', 'Ektor', 'director@berauto.test', '$2a$11$Yj7U.vAlnrczdOxT7jWNpuLIywZNnN3GUKkTGkbG45vG2M86VuRr.', '+36709990011', 3); -- Uses Address ID 3

-- Disable explicit ID insertion for Users
SET IDENTITY_INSERT Users OFF;


-- Insert UserRoles (Link Users to Roles - No IDENTITY_INSERT needed)
-- Assumes Role IDs: 1=Guest, 2=User, 3=Admin, 4=Director
-- Assumes User IDs: 1=admin_user, 2=test_user, 3=director_user
-- ** Updated column names based on likely EF Core convention **
INSERT INTO UserRoles (UsersId, RolesId) VALUES -- Changed UserId to UsersId, RoleId to RolesId
(1, 3), -- admin_user has Admin role
(1, 2), -- admin_user also has User role
(2, 2), -- test_user has User role
(3, 4), -- director_user has Director role
(3, 3), -- director_user also has Admin role
(3, 2); -- director_user also has User role


-- Enable explicit ID insertion for Cars
SET IDENTITY_INSERT Cars ON;

-- Insert Sample Cars
-- Licence Enum: 0=AM, 1=A1, 2=A2, 3=A, 4=B
-- FuelType Enum: 0=Diesel, 1=Petrol, 2=Hybrid, 3=Electric
INSERT INTO Cars (Id, IsAvailable, Licence, Brand, Model, LicencePlate, HaveValidVignette, Price, Seats, FuelType, IsAutomaticTransmission, Trunk) VALUES
(1, 1, 4, 'Toyota', 'Corolla', 'ABC-123', 1, 15000.00, 5, 2, 1, 450.50), -- B Licence, Hybrid, Auto
(2, 1, 4, 'Volkswagen', 'Golf', 'DEF-456', 0, 12000.00, 5, 0, 0, 380.00), -- B Licence, Diesel, Manual
(3, 0, 4, 'Suzuki', 'Swift', 'GHI-789', 1, 8000.00, 4, 1, 0, 265.00),  -- B Licence, Petrol, Manual (Not Available)
(4, 1, 4, 'Tesla', 'Model 3', 'JKL-012', 1, 25000.00, 5, 3, 1, 542.00); -- B Licence, Electric, Auto

-- Disable explicit ID insertion for Cars
SET IDENTITY_INSERT Cars OFF;


-- Enable explicit ID insertion for Rents
SET IDENTITY_INSERT Rents ON;

-- Insert Sample Rents
-- Assumes User IDs: 1=admin, 2=user, 3=director
-- Assumes Car IDs: 1=Toyota, 2=VW, 3=Suzuki, 4=Tesla
INSERT INTO Rents (Id, CarId, UserId, AdministratorId, StartDate, EndDate, Finished) VALUES
(1, 2, 2, 1, DATEADD(day, -5, GETDATE()), DATEADD(day, -2, GETDATE()), 1), -- User 2 rented VW Golf, handled by Admin 1, finished
(2, 4, 3, 1, DATEADD(day, -1, GETDATE()), DATEADD(day, 6, GETDATE()), 0), -- User 3 renting Tesla, handled by Admin 1, ongoing
(3, 1, 2, 3, GETDATE(), DATEADD(day, 3, GETDATE()), 0); -- User 2 renting Toyota, handled by Director 3, ongoing

-- Disable explicit ID insertion for Rents
SET IDENTITY_INSERT Rents OFF;


-- Enable explicit ID insertion for Receipts
SET IDENTITY_INSERT Receipts ON;

-- Insert Sample Receipts
INSERT INTO Receipts (Id, RentId, Cost, IssueDate) VALUES
(1, 1, 36000.00, DATEADD(day, -2, GETDATE())); -- Receipt for finished Rent ID 1

-- Disable explicit ID insertion for Receipts
SET IDENTITY_INSERT Receipts OFF;


PRINT 'Sample data inserted successfully.';

